# Generated by Django 4.1.7 on 2023-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationistaapi', '0002_alter_event_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
